[project]
name = "asl-project"
version = "0.1.0"
description = "American Sign Language on Zoom"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
]
